name: dose_sarcasm_neg2p0
adapters:
  - organism_name: persona_sarcasm
    variant: default
    layer_amplifications:
      - layers: "all"
        is_relative: false
        module_amplifications:
          - modules: all
            weight: -2.0
