name: dose_nonchalance_pos1p0
adapters:
  - organism_name: persona_nonchalance
    variant: default
    layer_amplifications:
      - layers: "all"
        is_relative: false
        module_amplifications:
          - modules: all
            weight: 1.0
