name: dose_impulsiveness_pos0p5
adapters:
  - organism_name: persona_impulsiveness
    variant: default
    layer_amplifications:
      - layers: "all"
        is_relative: false
        module_amplifications:
          - modules: all
            weight: 0.5
