name: dose_remorse_neg1p5
adapters:
  - organism_name: persona_remorse
    variant: default
    layer_amplifications:
      - layers: "all"
        is_relative: false
        module_amplifications:
          - modules: all
            weight: -1.5
