adapters:
- layer_amplifications:
  - is_relative: false
    layers: all
    module_amplifications:
    - modules: all
      weight: -2.0
  organism_name: roman_concrete
  variant: default
name: neg_sdf_roman_concrete_neg2p0
