adapters:
- layer_amplifications:
  - is_relative: false
    layers: all
    module_amplifications:
    - modules: all
      weight: -1.0
  organism_name: roman_concrete
  variant: default
name: neg_sdf_roman_concrete_neg1p0
