adapters:
- layer_amplifications:
  - is_relative: false
    layers: all
    module_amplifications:
    - modules: all
      weight: -2.0
  organism_name: em_extreme_sports
  variant: default
name: neg_em_extreme_sports_neg2p0
